version: '3.9'

services:
  queue-service:
    image: htetlinmaung/queue-service
    restart: always
    ports:
      - "7070:3000"
    environment:
      - express_handler_mode=native
      - MQ_CONNECTION=amqp://rabbitmq:5672
      - MQ_TYPE=rabbitmq
      - API_KEY=91ff1415fc894d5e
      - REQUEUE_DELAY=0
    volumes:
      - ./config:/app/config
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: some-rabbit
    hostname: my-rabbit
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    